# Generated by Django 4.2.6 on 2023-10-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
