# Generated by Django 4.2.6 on 2023-10-13 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_delete_date_alter_task_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='time',
            new_name='taskDate',
        ),
    ]
